
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\santiago\Desktop\is\aa\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    93.0,
    300.0,
    image=image_image_1
)

canvas.create_text(
    400.0,
    24.0,
    anchor="nw",
    text="BIENVENIDO",
    fill="#000000",
    font=("MicrosoftSansSerif", 32 * -1)
)

canvas.create_text(
    213.0,
    112.0,
    anchor="nw",
    text="Ingrese el ID del envío a modificar:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    626.0,
    119.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=559.0,
    y=102.0,
    width=134.0,
    height=33.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=714.0,
    y=97.0,
    width=50.0,
    height=45.0
)

canvas.create_text(
    305.0,
    175.0,
    anchor="nw",
    text="Datos actuales del envío:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

canvas.create_text(
    250.0,
    215.0,
    anchor="nw",
    text="Guía aérea",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    627.5,
    227.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=510.0,
    y=215.0,
    width=235.0,
    height=23.0
)

canvas.create_text(
    250.0,
    255.0,
    anchor="nw",
    text="Cliente:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    626.0,
    263.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=510.0,
    y=251.0,
    width=232.0,
    height=23.0
)

canvas.create_text(
    250.0,
    295.0,
    anchor="nw",
    text="Tipo de medicamento:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    628.0,
    304.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=512.0,
    y=292.0,
    width=232.0,
    height=23.0
)

canvas.create_text(
    252.0,
    335.0,
    anchor="nw",
    text="Destino:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    629.0,
    345.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=513.0,
    y=333.0,
    width=232.0,
    height=23.0
)

canvas.create_text(
    250.0,
    378.0,
    anchor="nw",
    text="Estado:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    628.0,
    387.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=512.0,
    y=375.0,
    width=232.0,
    height=23.0
)

canvas.create_text(
    250.0,
    418.0,
    anchor="nw",
    text="Temperatura:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    628.0,
    427.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=512.0,
    y=415.0,
    width=232.0,
    height=23.0
)

canvas.create_text(
    250.0,
    458.0,
    anchor="nw",
    text="Hora de entrega:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    626.0,
    467.5,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=510.0,
    y=455.0,
    width=232.0,
    height=23.0
)

canvas.create_text(
    250.0,
    498.0,
    anchor="nw",
    text="Ubicación actual:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    626.0,
    507.5,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=510.0,
    y=495.0,
    width=232.0,
    height=23.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=380.0,
    y=543.0,
    width=153.0,
    height=37.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=14.0,
    y=58.0,
    width=158.0,
    height=56.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=14.0,
    y=149.0,
    width=159.0,
    height=56.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=14.0,
    y=240.0,
    width=159.0,
    height=56.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=14.0,
    y=331.0,
    width=158.0,
    height=56.0
)
window.resizable(False, False)
window.mainloop()
