
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\santiago\Desktop\is\aa\build\assets\frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    93.0,
    300.0,
    image=image_image_1
)

canvas.create_text(
    400.0,
    24.0,
    anchor="nw",
    text="BIENVENIDO",
    fill="#000000",
    font=("MicrosoftSansSerif", 32 * -1)
)

canvas.create_text(
    219.0,
    127.0,
    anchor="nw",
    text="Crear nuevo envío:",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    244.0,
    222.0,
    anchor="nw",
    text="Ingrese el identificador del cliente:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    669.0,
    231.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=600.0,
    y=219.0,
    width=138.0,
    height=23.0
)

canvas.create_text(
    239.0,
    262.0,
    anchor="nw",
    text="Ingrese el número de guia aerea:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    670.0,
    272.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=600.0,
    y=260.0,
    width=140.0,
    height=23.0
)

canvas.create_text(
    241.0,
    301.0,
    anchor="nw",
    text="Ingrese el tipo de producto:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    670.5,
    313.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=600.0,
    y=301.0,
    width=141.0,
    height=23.0
)

canvas.create_text(
    238.0,
    344.0,
    anchor="nw",
    text="Ingrese el destino:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    670.0,
    353.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=600.0,
    y=341.0,
    width=140.0,
    height=23.0
)

canvas.create_text(
    242.0,
    382.0,
    anchor="nw",
    text="Ingrese la temperatura requerida:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    670.0,
    395.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=600.0,
    y=383.0,
    width=140.0,
    height=23.0
)

canvas.create_text(
    239.0,
    421.0,
    anchor="nw",
    text="Ingrese la hora de entrega:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    669.0,
    435.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=600.0,
    y=423.0,
    width=138.0,
    height=23.0
)

canvas.create_text(
    226.0,
    499.0,
    anchor="nw",
    text="Nuevo envío creado con ID:",
    fill="#000000",
    font=("MicrosoftSansSerif", 20 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    670.0,
    511.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=601.0,
    y=499.0,
    width=138.0,
    height=23.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=387.0,
    y=547.0,
    width=153.0,
    height=37.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=14.0,
    y=58.0,
    width=158.0,
    height=56.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=14.0,
    y=149.0,
    width=158.0,
    height=56.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=14.0,
    y=240.0,
    width=158.0,
    height=56.0
)
window.resizable(False, False)
window.mainloop()
